# action.yml
name: 'Download backup file'
description: 'Greet someone and record the time'
inputs:
  subaccount:  # id of input
    description: 'Subaccount Name'
    required: true
    default: 'World'
outputs:
  success: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subaccount }}
