# action.yml
name: 'Download backup file'
description: 'Download the configuration of a BusinessRules project as a .JSON file'
inputs:
  subaccount:
    description: 'Subaccount Name'
    required: true
    default: 'subaccountExample'
  projectId:
    description: 'Id of the BusinessRules project'
    required: true
    default: 'idExample'
outputs:
  success: # id of output
    description: 'Download succeed or Download failed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subaccount }}
    - ${{ inputs.projectId }}
