# action.yml
name: 'Download backup file'
description: 'Download the configuration of a BusinessRules project as a .JSON file'
inputs:
  subaccount:  # id of input
    description: 'Subaccount Name'
    required: true
    default: 'daljamsas'
  username:
    description: 'Username to authenticate against BusinessRules API'
    required: true
  password:
    description: 'Password to authenticate against BusinessRules API'
    required: true
outputs:
  success: # id of output
    description: 'Download succeed or Download failed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subaccount }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
