# action.yml
name: 'Download backup file'
description: 'Download the configuration of a BusinessRules project as a .JSON file'
inputs:
  subaccount:  # id of input
    description: 'Subaccount Name'
    required: true
    default: 'daljamsas'
outputs:
  success: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subaccount }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
