# This is a basic workflow to help you get started with Actions

name: NotifyBackup

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "export_job"
  backup_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Interrogate API and download .JSON file
      - name: Download backup file action step
        run: |
          # Parameters
          projectId="devProject"
          subacount="devSubaccount"
          
          # Prepare destination directory
          mkdir -p backups
          
          # Get formated date
          date=$(date +"%Y-%m-%dT%H-%M-%SZ")
          
          # Prepare filename (Example:  "Notify-Backup-2020-12-07T14-19-16Z.json")
          filename="Notify-Backup-${date}.json"
          
          # Prepare url
          url="https://jsonplaceholder.typicode.com/todos/1"
          
          # Interogate API to get configuration file
          wget -S $url -O backups/$filename --http-user=${{ secrets.BPMRULESREPOSITORYRULES_USERNAME }} --http-password=${{ secrets.BPMRULESREPOSITORYRULES_PASSWORD }}
      
      # Commit and push
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email ''
          git add -A backups
          git commit -m "Automated commit"        
          git push
